torch2424/vaporBoy

- package-lock.json
- package.json
- src/components/controlPanel/controlPanel.scss
- src/components/controlPanel/controlPanelSelect/controlPanelSelect.js
- src/components/controlPanel/settingsDisplay.js
- src/components/controlPanel/settingsDisplay.scss
- src/components/controlPanel/vaporBoyEffects/vaporBoyEffects.js
- src/components/controlPanel/vaporBoyEffects/vaporBoyEffects.sections.js
- src/components/controlPanel/vaporBoyOptions/vaporBoyOptions.js
- src/components/controlPanel/vaporBoyOptions/vaporBoyOptions.sections.js
- src/components/wasmboyCanvas/wasmboyCanvas.js
- src/pubx.config.js
- src/vaporBoyEffects.config.js
Started the effects settings to vaporboy, to allow for cool ROM gameplay experiences!
Also centralized the settings into one modal component, and added tuna for easy audio effects.
> Vaporboy Effects

- package-lock.json
> Fixed the package files

- package.json
This closes #21 
Simply fixed up and tested our SW with preact:serve, must have been fixed with #22 😄 ! Tested working with the live site
> Fixed up preact serve for SW testing

- src/components/controlPanel/ROMScraper/ROMScraper.js
- src/components/controlPanel/ROMSourceSelector/ROMSourceSelector.js
- src/components/controlPanel/controlPanelSelect/controlPanelSelect.js
- src/components/controlPanel/homebrew/homebrew.js
- src/components/controlPanel/loadStateList/loadStateList.js
- src/components/controlPanel/myCollection/myCollection.js
- src/components/controlPanel/settingsDisplay.js
- src/components/notification/notification.js
- src/components/notification/notification.scss
- src/components/vaporboyDesktop/vaporboyDesktop.js
- src/components/wasmboyCanvas/wasmboyCanvas.js
- src/components/wasmboyCanvas/wasmboyCanvas.scss
- src/index.js
- src/index.scss
- src/notification.messages.js
- src/pubx.config.js
> Implemented the Notification Service

- src/components/controlPanel/about/about.js
- src/components/controlPanel/about/about.scss
- src/components/controlPanel/controlPanel.scss
- src/components/controlPanel/controlPanelSelect/controlPanelSelect.js
- src/components/notification/notification.scss
- src/index.js
- src/index.scss
- src/notification.messages.js
closes #36 
closes #32 
As the title states, and did some nice little css improvements
> About Page, Pull To Refresh, And other Small Fixes

- src/components/controlPanel/ROMSourceSelector/ROMSourceSelector.js
- src/components/controlPanel/ROMSourceSelector/ROMSourceSelector.scss
- src/components/controlPanel/ROMlist.scss
- src/components/controlPanel/cartridge/cartridge.js
- src/components/controlPanel/homebrew/availableGames.js
- src/components/controlPanel/homebrew/homebrew.js
- src/components/controlPanel/myCollection/myCollection.js
- src/index.scss
- src/styles/_list-button.scss
> Allowed for Info Buttons on Homebrew, and Edit Buttons on Collection ROMs

- package-lock.json
- package.json
- src/components/controlPanel/ROMSourceSelector/ROMSourceSelector.js
- src/components/googlePicker/googlePicker.js
- src/notification.messages.js
- src/template.html
closes #40 
Simply taken from Wasmboy Debugger
> Added Google Drive as a ROM Source

- src/components/confirmationModal/confirmationModal.js
- src/components/controlPanel/ROMScraper/ROMScraper.js
- src/components/controlPanel/ROMScraper/manualInput/manualInput.js
- src/components/controlPanel/ROMScraper/searchInput/searchInput.js
- src/components/controlPanel/ROMScraper/searchInput/searchResult/searchResult.js
- src/components/controlPanel/ROMSourceSelector/ROMSourceSelector.js
- src/components/controlPanel/cartridge/cartridge.js
- src/components/controlPanel/controlPanel.js
- src/components/controlPanel/controlPanelSelect/controlPanelSelect.js
- src/components/controlPanel/homebrew/homebrew.js
- src/components/controlPanel/loadStateList/loadStateList.js
- src/components/controlPanel/myCollection/myCollection.js
- src/components/controlPanel/settingsDisplay.js
- src/components/controlPanel/vaporBoyOptions/vaporBoyOptions.sections.js
- src/components/notification/notification.js
- src/components/touchpad/controlPanelButton/controlPanelButton.js
- src/components/touchpad/expandButton/expandButton.js
- src/components/touchpad/touchpad.js
- src/components/touchpad/touchpad.scss
- src/components/touchpad/touchpadExpandedDesktop.scss
- src/components/wasmboyCanvas/wasmboyCanvas.js
- src/index.js
- src/index.scss
closes #33 
Just went through the app and made sure you can tab through everything and still play the games. Seems to be playable/navigatable now for a11y users :) Tested with Chromevox.
> A11y Support && Fixes

- package-lock.json
- package.json
- src/components/controlPanel/ROMScraper/ROMScraper.js
- src/components/controlPanel/ROMSourceSelector/ROMSourceSelector.js
- src/components/controlPanel/controlPanelSelect/controlPanelSelect.js
- src/components/controlPanel/homebrew/homebrew.js
- src/components/controlPanel/install/install.js
- src/components/controlPanel/loadStateList/loadStateList.js
- src/components/controlPanel/myCollection/myCollection.js
- src/components/controlPanel/settingsDisplay.js
- src/components/controlPanel/vaporBoyEffects/vaporBoyEffects.js
- src/components/controlPanel/vaporBoyOptions/vaporBoyOptions.js
- src/components/vaporboyDesktop/vaporboyDesktop.js
- src/components/wasmboyCanvas/wasmboyCanvas.js
- src/services/ROMCollection.js
closes #59 
closes #55 
closes #58 
This simply updates wasmboy, adds some error logging, fixes up other UX. With this PR Vaporboy can be considered a public beta with announcements coming soon!
> Updated WasmBoy, And Other Fixes

- package-lock.json
- package.json
- src/components/controlPanel/settingsDisplay.js
Now, Applying effects and settings works flawlessly, and we got all of the latests wasmboy fixes!
> Updated to wasmboy 0.1.4, and fixed up settings savestates

- package-lock.json
- package.json
This fixes issues with games being super slow on Mobile. 😄
> Updated Wasmboy and aesthetic-css

- README.md
- src/components/controlPanel/ROMScraper/searchInput/searchInput.js
- src/components/controlPanel/ROMSourceSelector/ROMSourceSelector.scss
- src/components/controlPanel/ROMlist.scss
- src/components/controlPanel/about/about.js
- src/components/controlPanel/about/about.scss
- src/components/controlPanel/controlPanelSelect/controlPanelSelect.scss
- src/components/controlPanel/myCollection/myCollection.js
- src/components/controlPanel/vaporBoyOptions/vaporBoyOptions.sections.js
- src/components/touchpad/touchpad.scss
- src/index.js
- src/index.scss
- src/template.html
- src/vaporboyOptions.config.js
closes #62 
This fixes a lot of small things that bothered me before we went beta. Beta should now be good to go!
> Small Beta Fixes

- src/index.js
- src/services/ROMCollection.js
closes #63 
This fixes the touch pad issue, also, remedies #66 for now 😄
> Touchpad re render

- package-lock.json
- package.json
- src/components/controlPanel/ROMScraper/manualInput/manualInput.js
- src/components/controlPanel/ROMScraper/searchInput/searchInput.js
- src/components/controlPanel/ROMSourceSelector/ROMSourceSelector.js
- src/components/controlPanel/about/about.js
- src/components/controlPanel/controlPanel.js
- src/components/controlPanel/controlPanelSelect/controlPanelSelect.js
- src/components/controlPanel/homebrew/homebrew.js
- src/components/controlPanel/install/install.js
- src/components/controlPanel/myCollection/myCollection.js
- src/components/controlPanel/settingsDisplay.js
- src/index.js
As the title states! This should give us more info on how to improve the app (e.g what is working and not UX wise), and should reduce the bundle size by 80KB.
> Updated Wasmboy, and Added some Analytics Events

- package-lock.json
- package.json
- src/assets/privacypolicy.html
- src/assets/robots.txt
- src/components/confirmationModal/confirmationModal.scss
- src/components/controlPanel/ROMScraper/searchInput/searchInput.js
- src/components/controlPanel/ROMSourceSelector/ROMSourceSelector.scss
- src/components/controlPanel/controlPanel.scss
- src/components/controlPanel/controlPanelSelect/controlPanelSelect.scss
- src/components/loadingModal/loadingModal.scss
- src/components/touchpad/gameboyButton/gameboyButton.js
- src/components/touchpad/gameboyDpad/gameboyDpad.js
- src/components/touchpad/touchpad.js
- src/components/touchpad/touchpad.scss
- src/components/touchpad/touchpadExpandedDesktop.scss
- src/components/touchpad/touchpadExpandedLandscape.scss
- src/components/touchpad/touchpadExpandedPortrait.scss
- src/components/touchpad/touchpadMobileLandscape.scss
- src/components/touchpad/touchpadMobilePortrait.scss
- src/components/vaporboyDesktop/vaporboyDesktop.scss
- src/components/vaporboyExpanded/vaporboyExpanded.scss
- src/components/vaporboyMobileLandscape/vaporboyMobileLandscape.scss
- src/components/vaporboyMobilePortrait/vaporboyMobilePortrait.scss
- src/components/wasmboyCanvas/wasmboyCanvas.js
- src/index.scss
closes #71 
relates to #47 
This does a ton of UX clean up, and gets mobile browsers a lot more solid CSS wise 😄 As well as other housekeeping items.
> A whole bunch of styling improvments, and general App maintenance

- package-lock.json
- package.json
- src/components/notification/notification.js
- src/components/wasmboyCanvas/wasmboyCanvas.js
- src/components/wasmboyCanvas/wasmboyCanvas.scss
- src/template.html
closes #75 
This updates wasmboy, closes the mentioned issue, and adds a nice pause reminder overlay
> Wasmboy Updated 0.2.0

- package-lock.json
- package.json
- src/components/controlPanel/about/about.js
> Updated wasmboy, and added Wasmboy version in About

- package-lock.json
- package.json
- src/components/controlPanel/myCollection/myCollection.js
- src/components/touchpad/touchpad.js
- src/components/vaporboyDesktop/vaporboyDesktop.js
- src/components/wasmboyCanvas/wasmboyCanvas.js
- src/template.html
related to https://github.com/torch2424/wasmBoy/pull/181
This fixes a bunch of safari load game issues with loading web workers, and autoplay no sound issues.
Went to an apple store, and found out vaporboy didn't work on iPhones 😮 , then upgraded to macOs mojave, and then all of a sudden I could reproduce 😢 
Loaded a ROM (web workers working), and Shows Sound icon (Fixed autoplay issue) 😄
> Fixed a bunch of Safari issues

- devops/scripts/buildVaporBoy.sh
- package-lock.json
- package.json
As the title states, super simple, and tried to remove logic out of the build script :smile:
> Improved legacy deployment process / Added github release support

- package.json
- src/components/controlPanel/controlPanel.scss
- src/components/controlPanel/controlPanelSelect/controlPanelSelect.js
- src/components/controlPanel/legacy/legacy.js
- src/components/controlPanel/legacy/legacy.scss
- src/components/controlPanel/loadStateList/loadStateList.js
- src/components/wasmboyCanvas/wasmboyCanvas.js
- src/services/ROMCollection.js
closes #102 
relates to #100 
**No version 0.1.0. It is there for placeholder**
> Added Legacy Support for Save States / Added way to access Legacy Vaporboy

- src/components/controlPanel/legacy/legacy.js
- src/components/controlPanel/loadStateList/loadStateList.js
I think this will fix things? Noticed this right after deploy, and dev shows something better than just nothing, so yeah!
> Can't navigate to index html, so going to / path for legacy

- src/components/touchpad/gameboyDpad/gameboyDpad.js
Makes pokemon silver feel sooo muh better :joy:
> Removed allow multiple directions for touch dpad

- package-lock.json
- package.json
- src/components/controlPanel/about/about.js
- src/components/controlPanel/about/about.scss
- src/components/controlPanel/controlPanelSelect/controlPanelSelect.js
- src/components/wasmboyCanvas/wasmboyCanvas.js
- src/notification.messages.js
- src/pubx.config.js
- src/vaporboyOptions.config.js
closes #113 
cc @Kcorab
This adds a "Speed Toggle" to the control panel, which allows for easily toggle between different preset speeds :smile: (1x, 1.5x, 2x, 0.5x). :smile:
> Added a Speed Toggle in the Control Panel / Added Quick Speed & Play Pause Hotkeys
